================
Mu Specification
================

This document aims to provide a detailed description of Mu, a micro virtual
machine, including its architecture, instruction set and type system.

Main specification:

- `Overview <overview>`__
- `Intermediate Representation <uvm-ir>`__
- `Intermediate Representation (Binary Form) <uvm-ir-binary>`__
- `Type System <type-system>`__
- `Instruction Set <instruction-set>`__
- `Common Instructions <common-insts>`__
- `Client Interface <uvm-client-interface>`__
- `Threads and Stacks <threads-stacks>`__
- `Memory and Garbage Collection <uvm-memory>`__
- `Memory Model <memory-model>`__
- `Portability and Implementation Advices <portability>`__
- `Native Interface <native-interface>`__

Platform-specific parts: These extends the main specification. The main
specification considers these parts as implementation-specific.

- `AMD64 Unix Native Interface <native-interface-x64-unix>`__

Working in progress:

(If there is any documents too experimental to be put into the content, it will
be listed here.)

- `Heap Allocation and Initialisation Language (HAIL) <hail>`__

Old documents:

- `Client Interface (old) <uvm-client-interface-old>`__


.. vim: tw=80
