================
Mu Specification
================

This document aims to provide a detailed description of Mu, a micro virtual
machine, including its architecture, instruction set and type system.

Contents:

- `Overview <overview>`__
- `Intermediate Representation <uvm-ir>`__
- `Intermediate Representation (Binary Form) <uvm-ir-binary>`__
- `Type System <type-system>`__
- `Instruction Set <instruction-set>`__
- `Common Instructions <common-insts>`__
- `Threads and Stacks <threads-stacks>`__
- `Memory and Garbage Collection <uvm-memory>`__
- `Memory Model <memory-model>`__
- `Client Interface <uvm-client-interface>`__
- `Portability and Implementation Advices <portability>`__

Working in progress:

(If there is any documents too experimental to be put into the content, it will
be listed here.)

- `Native Interface <native-interface>`__
- `AMD64 Native Interface <native-interface-x64>`__

.. vim: tw=80
