================
Mu Specification
================

This is a fork of the `Mu Specification` to support the long-demanded
"goto-with-value" form.

This document aims to provide a detailed description of Mu, a micro virtual
machine, including its architecture, instruction set and type system.

Main specification:

- `Overview <overview.rest>`__
- `Intermediate Representation <uvm-ir.rest>`__
- `Intermediate Representation (Binary Form) <uvm-ir-binary.rest>`__
- `Type System <type-system.rest>`__
- `Instruction Set <instruction-set.rest>`__
- `Common Instructions <common-insts.rest>`__
- `Client Interface <uvm-client-interface.rest>`__
- `Threads and Stacks <threads-stacks.rest>`__
- `Memory and Garbage Collection <uvm-memory.rest>`__
- `Memory Model <memory-model.rest>`__
- `Native Interface <native-interface.rest>`__
- `Heap Allocation and Initialisation Language (HAIL) <hail.rest>`__
- `Portability and Implementation Advices <portability.rest>`__

Platform-specific parts: These extends the main specification. The main
specification considers these parts as implementation-specific.

- `AMD64 Unix Native Interface <native-interface-x64-unix.rest>`__

Old documents:

- `Client Interface (old) <uvm-client-interface-old.rest>`__


.. vim: tw=80
