=========================================
Intermediate Representation (Binary Form)
=========================================

This document describes the binary form of the Mu intermediate representation.
For the text form, see `<uvm-ir>`__.

Overview
========

The Mu IR Binary Form is similar to the `Text Form <uvm-ir>`__ in structure,
but has notable differences.

Numerical IDs are used exclusively instead of textual names. The binary form
also provides a special "name binding" pseudo-top-level definition which
associates IDs with names.

Binary format
=============

A bundle in the binary form consists of many numbers encoded in bytes. All
numbers are encoded in **little endian** and are **tightly packed** which means
there are no padding bytes between two adjacent numbers. For floating point
numbers, it is equivalent to convert them bit-by-bit into integer types of the
same length and convert to bytes in little-endian.

Binary Types
------------

A sequence of bytes has a **binary type** which maps the bytes to the value they
represent. Possible binary types are:

i8, i16, i32, i64
    Integer types of the respective lengths.
float, double
    Floating point types of 32 bits and 64 bits, respectively.
idt
    Alias to i32. Used for IDs.
lent
    Alias to i16. Used for lengths of variable-length structures including the
    number of fields in a struct and the number of items in a parameter list.
aryszt
    Alias to i64. Used for the length of arrays.
opct
    Alias to i8. Used for instruction opcodes, operations or flags.
*other structures*
    One structure can contain other structures defined separately.

A table is used to represent a contiguous structure. The first row is a list of
binary types specifying the type of each column and the second row specifies for
each column either a symbolic name for that field or the exact binary content
expected. Such a structure consists of a sequence of numbers of the types of the
first row.

+-------+------------------+
| type1 | type2            |
+=======+==================+
| num   | or symbolic name | 
+-------+------------------+

Common Structures
=================

Some structures are common in multiple structures.

ID List
-------

An ID list, denoted as **idList**, is a list of IDs. It has the general form:

+------+-----+-----+-----+
| lent | idt | idt | ... |
+======+=====+=====+=====+
| nIDs | id1 | id2 | ... |
+------+-----+-----+-----+

``nIDs`` specifies the number of IDs and there are ``nIDs`` IDs following it.

Top-level Structure
===================

A bundle starts with a 4-byte magic "\x7F' 'U' 'I' 'R', or 0x7F 0x55 0x49
0x52. Then there are many top-level definitions until the end of the bundle.

Type Definition
---------------

Type definition has the following form:

+------+-----+------------------+
| opct | idt | type constructor |
+======+=====+==================+
| 0x01 | id  | cons             |
+------+-----+------------------+

``id`` is the identifier of the defined type. A type constructor follows the
opcode 0x01 and the ID. See `<type-system>`__ for a complete list of type
constructors.

    NOTE: this is equivalent to: ``.typedef id = cons``.

Function Signature Definition
-----------------------------

Function signature definition has the following form:

+------+-----+-------+----------+
| opct | idt | idt   | idList   |
+======+=====+=======+==========+
| 0x02 | id  | retty | paramtys |
+------+-----+-------+----------+

``id`` is the identifier of the defined function signature. ``retty`` is the
ID of the return type. ``paramtys`` is a list of IDs of its parameter types.

    NOTE: this is equivalent to: ``.funcsig id = retty (paramtys)``

Constant Definition
-------------------

Constant definition has the following form:

+------+-----+------+----------------------+
| opct | idt | idt  | constant constructor |
+======+=====+======+======================+
| 0x03 | id  | type | cons                 |
+------+-----+------+----------------------+

``id`` is the identifier of the defined constant. ``type`` is the type of the
constant and must match the constant constructor. A constant constructor follows
the type.

    NOTE: this is equivalent to: ``.const id <type> = cons``

Integer Constant Constructor
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

An integer constant constructor has the following form:

+------+--------+
| opct | i64    |
+======+========+
| 0x01 | number |
+------+--------+

``number`` is the integer constant number. If the integer constant has a type
with fewer bits, only the least significant bits are valid. The binary form
cannot encode integer constants larger than 64 bits.

    NOTE: this is equivalent to an integer literal in the text form.

Floating Point Constant Constructors
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A float constant constructor has the following form:

+------+--------+
| opct | float  |
+======+========+
| 0x02 | number |
+------+--------+

``number`` is the float constant number.

    NOTE: this is equivalent to a float literal in the text form.

A double constant constructor has the following form:

+------+--------+
| opct | double |
+======+========+
| 0x03 | number |
+------+--------+

``number`` is the double constant number.

    NOTE: this is equivalent to a double literal in the text form.

List Constant Constructor
~~~~~~~~~~~~~~~~~~~~~~~~~

A list constant constructor has the following form:

+------+---------+
| opct | idList  |
+======+=========+
| 0x04 | elems   |
+------+---------+

``elems`` is a list of IDs, each of which refers to another constant which is
the value of the corresponding field of the struct or element of array/vector.

    NOTE: this is equivalent to the struct literal ``{elems}`` in the text
    form.

NULL Constant Constructor
~~~~~~~~~~~~~~~~~~~~~~~~~

A NULL constant constructor has the following form:

+------+
| opct |
+======+
| 0x05 |
+------+

    NOTE: this is equivalent to the ``NULL`` keyword in the text form.

Global Cell Definition
----------------------

Global cell definition has the following form:

+------+-----+------+
| opct | idt | idt  |
+======+=====+======+
| 0x04 | id  | type |
+------+-----+------+

``id`` is the ID of the defined global cell. ``type`` is the type of the global
cell.

    NOTE: this is equivalent to: ``.global id <type>``

Function Definition and Declaration
-----------------------------------

Function declaration has the following form:

+------+-----+-----+
| opct | idt | idt |
+======+=====+=====+
| 0x05 | id  | sig |
+------+-----+-----+

``id`` is the ID of the declared function. ``sig`` is the function signature of
it.

    NOTE: this is equivalent to: ``.funcdecl id <sig>``

Function definition has the following form:

+------+-----+-------+-----+--------+---------------+
| opct | idt | idt   | idt | idList | function body |
+======+=====+=======+=====+========+===============+
| 0x06 | id  | verid | sig | params | body          |
+------+-----+-------+-----+--------+---------------+

``id`` is the ID of the defined function. ``verid`` is the ID of the version of
the function. ``sig`` is the function signature of it. ``params`` is a list of
IDs, each of which is the ID of its parameter. ``body`` is the function body.

    NOTE: this is equivalent to: ``.funcdef id VERSION verid <sig> (params) {
    body }``

Function Body
=============

A **function body** has the following form:

+------+-------------+-------------+-----+
| lent | basic block | basic block | ... |
+======+=============+=============+=====+
| nbbs | bb1         | bb2         | ... |
+------+-------------+-------------+-----+

``nbbs`` is the number of basic blocks. ``bbx`` are basic blocks.

A **basic block** has the following form:

+-----+--------+-------------+-------------+-----+
| idt | lent   | instruction | instruction | ... |
+=====+========+=============+=============+=====+
| id  | ninsts | inst1       | inst2       | ... |
+-----+--------+-------------+-------------+-----+

``id`` is the ID of the basic block. Every basic block must have an ID,
*even the entry block*. ``ninsts`` is the number of instructions in the current
basic block. There are ninsts basic blocks following the header.

An **instruction** has the following form:

+-----+------------------+
| idt | instruction body |
+=====+==================+
| id  | instbody         |
+-----+------------------+

``id`` is the ID of the instruction. ``instbody`` is instruction body which is
specific to each instruction. See `<instruction-set>`__ for an exhaustive list.

Function Exposing Definition
============================

Function declaration has the following form:

+------+-----+------+----------+--------+
| opct | idt | idt  | opct     | idt    |
+======+=====+======+==========+========+
| 0x07 | id  | func | callConv | cookie |
+------+-----+------+----------+--------+

``id`` is the ID of the exposed value. ``func`` is the ID of the function to
expose. ``callConv`` is the calling convention flag. ``cookie`` is the cookie,
the ID of an ``int<64>`` constant.

Name Binding
============

Name binding is a definition specific to the binary form. It binds a name to an
ID. It is designed for debugging purposes and is optional. The name must be a
valid textual global identifier (including the prefix '@').

A name binding has the following form:

+------+-----+--------+-------+-------+-----+
| opct | idt | lent   | i8    | i8    | ... |
+======+=====+========+=======+=======+=====+
| 0x08 | id  | nbytes | byte1 | byte2 | ... |
+------+-----+--------+-------+-------+-----+

``id`` is the ID to bind. ``nbytes`` is the number of bytes in the name and
``bytex`` is the value of each byte.

The name is encoded in ASCII and must follow the rules of global names, local
names and allowed characters as defined in `<uvm-ir>`__.

Example
=======

Here is a side-by-side translation of a bundle from the text form to the binary
form::

    // magic
    // 7f 55 49 52

    //       @i8
    .typedef @65536     = int <8>
    // 01    00 00 01 00  01  08

    //       @i64
    .typedef @65537     = int <64>
    // 01    01 00 01 00  01  40
    
    //       @float
    .typedef @65538     = float
    // 01    02 00 01 00  02

    //       @double
    .typedef @65539     = double
    // 01    03 00 01 00  03

    //       @refi8              @i8
    .typedef @65540     = ref   <@65536>
    // 01    04 00 01 00  04    00 00 01 00

    //       @irefi64            @i64
    .typedef @65541     = iref  <@65537>
    // 01    05 00 01 00  05    01 00 01 00

    //       @wreff                  @float
    .typedef @65542     = weakref   <@65538>
    // 01    06 00 01 00  06        02 00 01 00

    //       @s                     2 flds  @i8             @i64
    .typedef @65543     = struct    <       @65536          @65537>
    // 01    07 00 01 00  07        02 00   00 00 01 00     01 00 01 00

    //       @a                      @i8
    .typedef @65544     = array     <@65536         10>
    // 01    08 00 01 00  08        00 00 01 00     0a 00 00 00 00 00 00 00

    //       @h                      @i64           @i8
    .typedef @65545     = hybrid    <@65537         @65536>
    // 01    09 00 01 00  09        00 00 01 00     01 00 01 00

    //       @void
    .typedef @65546     = void
    // 01    0a 00 01 00  0a

    //       @f                   @sig2
    .typedef @65547     = funcref<@65552>
    // 01    0b 00 01 00  0b    10 00 01 00

    //       @thread
    .typedef @65548     = threadref
    // 01    0c 00 01 00  0c

    //       @stack
    .typedef @65549     = stackref
    // 01    0d 00 01 00  0d

    //       @tagref64
    .typedef @65550     = tagref64
    // 01    0e 00 01 00  0e

    //       @vec_4xfloat
    .typedef @65793     = vector < @float       4     >
    // 01    01 01 01 00  0f       02 00 01 00  04 00

    //       @sig1        @void
    .funcsig @65551     = @65546        ()      // void ()
    // 02    0f 00 01 00  0a 00 01 00   00 00

    //       @sig2        @i64                 @i64         @irefi64
    .funcsig @65552     = @65537        (      @65537       @65541)
    // 02    10 00 01 00  0a 00 01 00   02 00  01 00 01 00  05 00 01 00

    //      @const0       @i8
    .const  @65568       <@65536>    =  42
    // 03   20 00 01 00   00 00 01 00   01  2a 00 00 00 00 00 00 00

    //      @const1       @i64
    .const  @65569       <@65537>    =  0x123456789abcdef0
    // 03   21 00 01 00   01 00 01 00   01  f0 de bc 9a 78 56 34 12

    //      @const2       @float
    .const  @65570       <@65538>    =  1234.5f
    // 03   22 00 01 00   02 00 01 00   02  00 50 9a 44

    //      @const3       @double
    .const  @65571       <@65539>    =  1234.5d
    // 03   23 00 01 00   03 00 01 00   03  00 00 00 00 00 4a 93 40

    //      @const4       @s                2 flds   @const0      @const1
    .const  @65572       <@65543>    =  {            @65568       @65569 }
    // 03   24 00 01 00   07 00 01 00   04  02 00    20 00 01 00  21 00 01 00

    //      @const5       @refi8
    .const  @65573       <@65540>    =  NULL
    // 03   25 00 01 00   04 00 01 00   05

    //      @gd0          @refi8
    .global @65584       <@65540>
    // 04   30 00 01 00   04 00 01 00

    //          @func0       @sig1
    .funcdecl   @65600      <@65551>
    // 05       40 00 01 00  0f 00 01 00

    //          @func1       @sig2                  @sig2_v1    2 params    %p0          %p1          1 basic block
    .funcdef    @65601      <@65552>        VERSION @65794      (           %65602       %65603)      {
    // 06       41 00 01 00  10 00 01 00            02 01 00 00 02 00       42 00 01 00  43 00 01 00  01 00

    //  %entry       2 instructions
        %65604:
    //  44 00 01 00  02 00

            // %v1                           @i64         %p1               no exception clause
            %65605 =        LOAD NOT_ATOMIC <@65537>      %65603
            // 45 00 01 00  1a   00          01 00 01 00  43 00 01 00       00 00 00 00 00 00 00 00

            // %v2                @i64          %p0          %v1            
            %65606 =        SDIV <@65537>       %65602       %65605         EXC %cont %catch
            // 46 00 01 00  04   01 00 01 00    42 00 01 00  45 00 01 00    48 00 01 00 49 00 01 00

    //  %cont        1 instruction
        %65608:
    //  48 00 01 00  01 00

            %65607 =        RET  <@65537>       %v2
            // 47 00 01 00  63   01 00 01 00    46 00 01 00

    //  %catch       1 instruction
        %65609:
    //  49 00 01 00  01 00

            %65610 =        RET  <@65537>       %v1
            // 4a 00 01 00  63   01 00 01 00    45 00 01 00
        
        
    }

    //      @func0_exp  @func0       #DEFAULT @const1
    .expose @65616 =    @65600       0 T      @65569
    // 07  50 00 01 00  40 00 01 00  00       21 00 01 00

    // Bind ID 65604 with the string "@sig2_v1.entry"
    // 08  44 00 01 00  06  40 73 69 67 32 5f 76 31 2e 65 6e 74 72 79

.. vim: textwidth=80
